services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - /backend/__pycache__
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/backend
    networks:
      - agentic-ai-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/v1
      - NEXT_PUBLIC_FRONTEND_URL=http://frontend:3000
    depends_on:
      - backend
    networks:
      - agentic-ai-network

networks:
  agentic-ai-network:
    driver: bridge
