#!/bin/bash
# Start Cloudflare tunnels for local development and export URLs for docker-compose
# Usage: source start-local-tunnels.sh

set -e

echo "Starting Cloudflare tunnels..."

# Create temp files for tunnel output
GREEN_LOG=$(mktemp)
WHITE1_LOG=$(mktemp)
WHITE2_LOG=$(mktemp)

# Cleanup function
cleanup() {
    echo ""
    echo "Shutting down tunnels..."
    kill $GREEN_PID $WHITE1_PID $WHITE2_PID 2>/dev/null || true
    rm -f "$GREEN_LOG" "$WHITE1_LOG" "$WHITE2_LOG"
    echo "Tunnels stopped."
}
trap cleanup EXIT

# Start tunnels in background, capturing output
cloudflared tunnel --url http://localhost:8011 2>&1 | tee "$GREEN_LOG" &
GREEN_PID=$!

cloudflared tunnel --url http://localhost:8012 2>&1 | tee "$WHITE1_LOG" &
WHITE1_PID=$!

cloudflared tunnel --url http://localhost:8013 2>&1 | tee "$WHITE2_LOG" &
WHITE2_PID=$!

echo "Waiting for tunnels to establish..."
sleep 5

# Function to extract URL from cloudflared output
extract_url() {
    grep -o 'https://[a-zA-Z0-9-]*\.trycloudflare\.com' "$1" | head -1
}

# Extract URLs (retry a few times as tunnels may take time to establish)
for i in {1..10}; do
    GREEN_URL=$(extract_url "$GREEN_LOG")
    WHITE1_URL=$(extract_url "$WHITE1_LOG")
    WHITE2_URL=$(extract_url "$WHITE2_LOG")
    
    if [[ -n "$GREEN_URL" && -n "$WHITE1_URL" && -n "$WHITE2_URL" ]]; then
        break
    fi
    echo "Waiting for tunnel URLs... (attempt $i/10)"
    sleep 2
done

# Check if we got all URLs
if [[ -z "$GREEN_URL" || -z "$WHITE1_URL" || -z "$WHITE2_URL" ]]; then
    echo "ERROR: Failed to get all tunnel URLs"
    echo "  GREEN_URL: ${GREEN_URL:-NOT FOUND}"
    echo "  WHITE1_URL: ${WHITE1_URL:-NOT FOUND}"
    echo "  WHITE2_URL: ${WHITE2_URL:-NOT FOUND}"
    exit 1
fi

# Extract hostnames (without https://)
GREEN_HOST=${GREEN_URL#https://}
WHITE1_HOST=${WHITE1_URL#https://}
WHITE2_HOST=${WHITE2_URL#https://}

# Export environment variables
export GREEN_AGENT_URL="$GREEN_URL"
export GREEN_AGENT_URL_NO_PROTOCOL="$GREEN_HOST"
export WHITE_AGENT_1_URL="$WHITE1_URL"
export WHITE_AGENT_1_URL_NO_PROTOCOL="$WHITE1_HOST"
export WHITE_AGENT_2_URL="$WHITE2_URL"
export WHITE_AGENT_2_URL_NO_PROTOCOL="$WHITE2_HOST"
export HTTPS_ENABLED=true

# Write to .env.local for docker-compose
ENV_FILE=".env.local"
cat > "$ENV_FILE" << EOF
# Auto-generated by start-local-tunnels.sh
# Generated at: $(date)

GREEN_AGENT_URL=$GREEN_URL
GREEN_AGENT_URL_NO_PROTOCOL=$GREEN_HOST
WHITE_AGENT_1_URL=$WHITE1_URL
WHITE_AGENT_1_URL_NO_PROTOCOL=$WHITE1_HOST
WHITE_AGENT_2_URL=$WHITE2_URL
WHITE_AGENT_2_URL_NO_PROTOCOL=$WHITE2_HOST
HTTPS_ENABLED=true
EOF

echo ""
echo "=========================================="
echo "Cloudflare Tunnels Established!"
echo "=========================================="
echo ""
echo "Green Agent:   $GREEN_URL"
echo "White Agent 1: $WHITE1_URL"
echo "White Agent 2: $WHITE2_URL"
echo ""
echo "Environment variables exported and saved to $ENV_FILE"
echo ""
echo "To start docker-compose with these URLs, run in another terminal:"
echo "  docker compose -f docker-compose.local.yml --env-file .env.local up --build"
echo ""
echo "Press Ctrl+C to stop tunnels..."
echo ""

# Keep script running to maintain tunnels
wait
