[green_agent]
endpoint = "http://127.0.0.1:9009"
cmd = "python -m agentbeats.dnd.dnd_master --host 127.0.0.1 --port 9009"

[[participants]]
role = "player0"
endpoint = "http://127.0.0.1:9019"
cmd = "python agentbeats/dnd/player.py --host 127.0.0.1 --port 9019"

[[participants]]
role = "player1"
endpoint = "http://127.0.0.1:9018"
cmd = "python agentbeats/dnd/player.py --host 127.0.0.1 --port 9018"

[config]
scenario = "A dragon threatens the village of Eldreth. The players must work together to defeat it."
num_turns = 5
